// Auto-generated by scripts/plugin-sync.ts. DO NOT EDIT.
import type { HomepagePlugin } from './runtime'

import { plugins as corePlugins } from './core/plugin'
import { plugins as bookmarksPlugins } from './bookmarks/plugin'
import { plugins as heatmapPlugins } from './heatmap/plugin'
import { plugins as kanbanPlugins } from './kanban/plugin'
import { plugins as notesPlugins } from './notes/plugin'
import { plugins as pomodoroPlugins } from './pomodoro/plugin'
import { plugins as streakPlugins } from './streak/plugin'
import { plugins as todoPlugins } from './todo/plugin'
import { plugins as examplePlugins } from '@ext/example/plugin'
import { plugins as deepseekPlugins } from '@ext/my-tabstart-plugins/deepseek/plugin'
import { plugins as liquidGlassPlugins } from '@ext/my-tabstart-plugins/liquid-glass/plugin'
import { plugins as opencodeGoPlugins } from '@ext/my-tabstart-plugins/opencode-go/plugin'

export interface EnabledPluginModule {
  dir: string
  plugins: HomepagePlugin[]
}

export const enabledPluginModules: EnabledPluginModule[] = [
  { dir: 'core', plugins: corePlugins },
  { dir: 'bookmarks', plugins: bookmarksPlugins },
  { dir: 'heatmap', plugins: heatmapPlugins },
  { dir: 'kanban', plugins: kanbanPlugins },
  { dir: 'notes', plugins: notesPlugins },
  { dir: 'pomodoro', plugins: pomodoroPlugins },
  { dir: 'streak', plugins: streakPlugins },
  { dir: 'todo', plugins: todoPlugins },
  { dir: 'example', plugins: examplePlugins },
  { dir: 'my-tabstart-plugins/deepseek', plugins: deepseekPlugins },
  { dir: 'my-tabstart-plugins/liquid-glass', plugins: liquidGlassPlugins },
  { dir: 'my-tabstart-plugins/opencode-go', plugins: opencodeGoPlugins },
]
